SELECT DISTINCT
    le.COUNTRY,
    es.EBA_SERVICES_ID,
    eef.EBA_CODE,
    a.ACTIVITY_ID,
    a.ACTIVITY_LABEL
FROM
    PHI_T_ACTIVITY a
    LEFT OUTER JOIN PHI_T_REL_ACTIVITY_ENTITY rae ON a.ACTIVITY_ID = rae.ACTIVITY_ID
    LEFT OUTER JOIN PHI_T_LEGAL_ENTITY le ON rae.LEGAL_ENTITY_ID = le.LEGAL_ENTITY_ID
    LEFT OUTER JOIN PHI_T_ACTIVITY_TYPE_CATEGORY atc ON a.ACTIVITY_TYPE_ID = atc.ACTIVITY_TYPE_ID
    LEFT OUTER JOIN PHI_T_REL_EBA_SERVICES_ENTITY_TYPE resat ON a.ACTIVITY_TYPE_ID = resat.ACTIVITY_TYPE_ID
    LEFT OUTER JOIN PHI_T_EBA_SERVICES es ON resat.EBA_SERVICES_ID = es.EBA_SERVICES_ID
    LEFT OUTER JOIN PHI_T_EBA_ECO_FUNCTION eef ON atc.EBA_ECO_FUNCTION_ID = eef.EBA_ECO_FUNCTION_ID
ORDER BY
    le.COUNTRY,
    es.EBA_SERVICES_ID,
    a.ACTIVITY_ID;