package car_backend.repository.reports;

import car_backend.model.reports.ContractReport;
import jakarta.transaction.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

@Repository
public interface ReportContractRepository extends JpaRepository<ContractReport, String> {

    @Modifying
    @Transactional
    @Query(value = "TRUNCATE TABLE PHI_T_REPORT_CONTRACT_REPOSITORY_FINAL", nativeQuery = true)
    void truncateReportTable();

    @Modifying
    @Query(value = "BEGIN " +
            "INSERT INTO PHI_T_REPORT_CONTRACT_REPOSITORY_FINAL (" +
            "IDENTIFIER, SERVICE_IDENTIFIER, START_DATE_OF_THE_CONTRACT, END_DATE_OF_THE_CONTRACT, " +
            "NEXT_RENEWAL_DATE, SERVICE_RECIPIENT_NAME, PROVIDER_ENTITY_NAME, PROVIDER_ENTITY_CODE, " +
            "PROVIDER_ENTITY_TYPE_OF_CODE, PROVIDER_ENTITY_REGISTERED_ADDRESS, PROVIDER_PARENT_NAME, " +
            "PROVIDER_PARENT_CODE, PROVIDER_PARENT_TYPE_OF_CODE, SUBCONTRACTOR, " +
            "PART_OF_THE_GROUP_SERVICE_DELIVERY, PART_OF_THE_RESOLUTION_GROUP, GROUP_DEPARTMENT_RESPONSIBLE, " +
            "BRIEF_DESCRIPTION_OF_THE_SERVICE, PRICING_STRUCTURE_PREDICTABLE, ESTIMATED_TOTAL_ANNUAL_BUDGET_COST, " +
            "DEGREE_OF_CRITICALITY, CRITICAL_FUNCTION_FOR_SERVICE, CORE_BUSINESS_LINES_FOR_SERVICE, " +
            "RESOLUTION_GROUPS_FOR_SERVICE, NAME_OF_ALTERNATIVE_SERVICE_PROVIDER, JURISDICTION_OF_CONTRACT, " +
            "GOVERNING_LAW, COUNTRIES_WHERE_SERVICES_PROVIDED, RESOLUTION_RESILIENT_CONTRACT, " +
            "PENALTIES_FOR_SUSPENSION, TRIGGERS_FOR_EARLY_TERMINATION, TERMINATION_NOTICE_PERIOD_PROVIDER, " +
            "DURATION_POST_TERMINATION_ASSISTANCE, RELATIONSHIPS_BETWEEN_CONTRACTS, CONDITIONS_OF_PAYMENT, " +
            "EXISTENCE_AUTOMATIC_RENEWAL_CLAUSES, QUANTITATIVE_PERFORMANCE_TARGETS, QUALITATIVE_PERFORMANCE_TARGETS, " +
            "PARTIES_ALLOWED_TO_TERMINATE, ESTIMATED_TIME_FOR_SUBSTITUTABILITY" +
            ") " +
            "SELECT DISTINCT " +
            "c.CONTRACT_ID, a.ACTIVITY_ID, c.STARTING_DATE, c.INITIAL_END_DATE, c.NEXT_RENEWAL_DATE, " +
            "le.LEGAL_ENTITY_LABEL, " +
            "COALESCE(s.SUPPLIER_LABEL, le.LEGAL_ENTITY_LABEL), " +
            "COALESCE(s.LEI_SUPPLIER_CODE, s.CRN_SUPPLIER, s.SIREN_SIRET_SUPPLIER_CODE, le.LEI_CODE, le.CRN_CODE, le.SIREN_CODE), " +
            "CASE WHEN s.LEI_SUPPLIER_CODE IS NOT NULL THEN 'LEI' WHEN s.CRN_SUPPLIER IS NOT NULL THEN 'CRN' " +
            "WHEN s.SIREN_SIRET_SUPPLIER_CODE IS NOT NULL THEN 'SIREN_SIRET' WHEN le.LEI_CODE IS NOT NULL THEN 'LEI' " +
            "WHEN le.CRN_CODE IS NOT NULL THEN 'CRN' WHEN le.SIREN_CODE IS NOT NULL THEN 'SIREN_SIRET' ELSE NULL END, " +
            "COALESCE(s.SUPPLIER_ADDRESS, le.LEGAL_ENTITY_ADDRESS), " +
            "COALESCE(sp.SUPPLIER_LABEL, lep.LEGAL_ENTITY_LABEL), " +
            "COALESCE(sp.LEI_SUPPLIER_CODE, sp.CRN_SUPPLIER, sp.SIREN_SIRET_SUPPLIER_CODE, lep.LEI_CODE, lep.CRN_CODE, lep.SIREN_CODE), " +
            "CASE WHEN sp.LEI_SUPPLIER_CODE IS NOT NULL THEN 'LEI' WHEN sp.CRN_SUPPLIER IS NOT NULL THEN 'CRN' " +
            "WHEN sp.SIREN_SIRET_SUPPLIER_CODE IS NOT NULL THEN 'SIREN_SIRET' WHEN lep.LEI_CODE IS NOT NULL THEN 'LEI' " +
            "WHEN lep.CRN_CODE IS NOT NULL THEN 'CRN' WHEN lep.SIREN_CODE IS NOT NULL THEN 'SIREN_SIRET' ELSE NULL END, " +
            "c.SUBCONTRACTING, " +
            "le.REGULATED, " +
            "le.PART_OF_THE_RESOLUTION_GROUP, " +
            "c.RESPONSIBLE_DEPARTMENT, " +
            "c.SERVICE_DESCRIPTION, " +
            "c.PREDICTABLE_PRICING_STRUCTURE, c.ESTIMATED_TOTAL_ANNUAL_BUDGET, " +
            "a.CRITICAL_ESSENTIAL, ef.EBA_CODE, ebl.CORE_BUSINESS_LINE_NAME, le.RESOLUTION_GROUP, " +
            "c.ALTERNATIVE_SERVICE_PROVIDER, c.JURISDICTION, c.GOVERNING_LAW, c.COUNTRY_OF_SERVICE, " +
            "c.RESOLUTION_RESILIENCE_FEATURES, c.PENALTIES, c.TRIGGER_FOR_EARLY_TERMINATION, " +
            "c.TERMINATION_NOTICE_PERIOD, c.POST_TERMINATION_ASSISTANCE_DURATION, c.RELATED_FRAMEWORK_AGREEMENT, " +
            "c.CONDITIONS_OF_PAYMENT, c.AUTOMATIC_RENEWAL_CLAUSES, c.QUANTITATIVE_PERFORMANCE_TARGETS, " +
            "c.QUALITATIVE_PERFORMANCE_TARGETS, c.PARTIES_ALLOWED_TO_TERMINATE, c.ESTIMATED_TIME_FOR_SUBSTITUTABILITY " +
            "FROM PHI_T_CONTRACT c " +
            "LEFT JOIN PHI_T_REL_CONTRACT_SUPPLIER rcs ON c.CONTRACT_ID = rcs.CONTRACT_ID " +
            "LEFT JOIN PHI_T_SUPPLIER s ON rcs.SUPPLIER_ID = s.SUPPLIER_ID " +
            "LEFT JOIN PHI_T_SUPPLIER sp ON s.SUPPLIER_PARENT_ID = sp.SUPPLIER_ID " +
            "LEFT JOIN PHI_T_REL_ACTIVITY_PROVIDER_ACTIVITY rapa ON c.CONTRACT_ID = rapa.CONTRACT_ID " +
            "LEFT JOIN PHI_T_ACTIVITY a ON rapa.PROVIDER_ACTIVITY_ID = a.ACTIVITY_ID " +
            "LEFT JOIN PHI_T_REL_ACTIVITY_ENTITY rae ON a.ACTIVITY_ID = rae.ACTIVITY_ID " +
            "LEFT JOIN PHI_T_LEGAL_ENTITY le ON rae.LEGAL_ENTITY_ID = le.LEGAL_ENTITY_ID " +
            "LEFT JOIN PHI_T_LEGAL_ENTITY lep ON le.LEGAL_ENTITY_PARENT_ID = lep.LEGAL_ENTITY_ID " +
            "LEFT JOIN PHI_T_ACTIVITY_TYPE_CATEGORY atc ON a.ACTIVITY_TYPE_ID = atc.ACTIVITY_TYPE_ID " +
            "LEFT JOIN PHI_T_EBA_ECO_FUNCTION ef ON atc.EBA_ECO_FUNCTION_ID = ef.EBA_ECO_FUNCTION_ID " +
            "LEFT JOIN PHI_T_EBA_BUSINESS_LINE ebl ON atc.CORE_BUSINESS_LINE_ID = ebl.CORE_BUSINESS_LINE_ID; " +
            "END;", nativeQuery = true)
    void insertReportTable();

}
