  CREATE TABLE "HPIOA"."PHI_T_REPORT_Z01_STEP_03" 
   (	"ACTIVITY_ID" VARCHAR2(400 BYTE) NOT NULL ENABLE, 
	"ACTIVITY_CATEGORY_TYPE" VARCHAR2(400 BYTE), 
	"UNIQUE_SERVICE_TITLE_BANK_TAXO" VARCHAR2(800 BYTE), 
	"LEGAL_ENTITY_LABEL_FROM_REF" VARCHAR2(400 BYTE), 
	"LEGAL_ENTITY_LABEL" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "HPICA1" ;

