create or replace PACKAGE BODY P_REPORT_SERVICE_CATALOGUE AS

PROCEDURE TRUNCATE_SERVICE_CATALOGUE IS
BEGIN
EXECUTE IMMEDIATE 'TRUNCATE TABLE PHI_T_REPORT_SERVICE_CATALOGUE';
END TRUNCATE_SERVICE_CATALOGUE;
---------------------------------------------------------------------------------------------------------------------------------------------

PROCEDURE INSERT_INFO_REPORT_SERVICE_CATALOGUE IS
BEGIN
INSERT INTO PHI_T_REPORT_SERVICE_CATALOGUE (
    SERVICE_IDENTIFIER_0005,
    SERVICE_TYPE_0010,
    UNIQUE_SERVICE_TITLE_BK_TAXO_0015,
    SERVICE_DESCRIPTION_0020,
    SERVICE_PROVIDER_ENTITY_NAME_0030,
    SERVICE_PROVIDER_ENTITY_DEPARTMENT_NAME_0040,
    SERVICE_PROVIDER_ENTITY_CODE_0050,
    SERVICE_RECIPIENT_ENTITY_NAME_0060,
    SERVICE_RECIPIENT_ENTITY_CODE_0070,
    DELIVERY_MODEL_0080,
    CRITICAL_FUNCTION_ID_0090,
    CORE_BUSINESS_LINE_0100,
    SUBSTITUTABILITY_0110,
    COST_0120,
    CONTACT_ID_0130,
    INCLUSION_OF_RESOLUTION_0140,
    COUNTRY_0150,
    MACRO_BUSINESS_LINE_0160,
    MACRO_PROCESS_0170,
    PROCESS_0180,
    SUB_PROCESS_0190,
    ACTIVITY_CATEGORY_0200,
    IS_BLOKING_0210
)
SELECT DISTINCT
    a.ACTIVITY_ID,
    COALESCE(es.EBA_SERVICES_ID, '#UNV'),
    CASE
        WHEN a.ACTIVITY_LABEL IS NOT NULL
        THEN CONCAT(CONCAT(a.ACTIVITY_ID, '_'), a.ACTIVITY_LABEL)
        ELSE CONCAT(a.ACTIVITY_ID, '_#UNV')
    END,
    COALESCE(a.ACTIVITY_DESCRIPTION, '#UNV'),
    COALESCE(sp.ORGANIZATIONAL_UNIT_NAME, '#UNV'),
    COALESCE(sp.ORGANIZATIONAL_UNIT_NAME, '#UNV'),
    COALESCE(sp.ORGANIZATIONAL_UNIT_CODE, '#UNV'),
    COALESCE(sr.ORGANIZATIONAL_UNIT_NAME, '#UNV'),
    COALESCE(sr.ORGANIZATIONAL_UNIT_CODE, '#UNV'),
    COALESCE(dm.DELIVERY_MODEL_NAME, '#UNV'),
    COALESCE(LISTAGG(cf.CRITICAL_FUNCTION_ID, ';') WITHIN GROUP (ORDER BY cf.CRITICAL_FUNCTION_ID), '#UNV'),
    COALESCE(ebl.CORE_BUSINESS_LINE_ID, '#UNV'),
    COALESCE(a.SUBSTITUTABILITY, '#UNV'),
    COALESCE(a.COST_INFO, '#UNV'),
    COALESCE(c.CONTRACT_ID, 'N/A'),
    COALESCE(a.RESOLUTION_CLAUSE, 'Not applicable'),
    COALESCE(a.COUNTRY, '#UNV'),
    COALESCE(mbl.MACRO_BUSINESS_LINE_NAME, '#UNV'),
    COALESCE(mp.MACRO_PROCESS_NAME, '#UNV'),
    COALESCE(p.PROCESS_NAME, '#UNV'),
    COALESCE(sp_sub.SUB_PROCESS_NAME, '#UNV'),
    COALESCE(ac.ACTIVITY_CATEGORY_NAME, '#UNV'),
    'Yes'
FROM
    PHI_T_ACTIVITY a
    LEFT OUTER JOIN PHI_T_ACTIVITY_TYPE_CATEGORY atc
        ON a.ACTIVITY_TYPE_ID = atc.ACTIVITY_TYPE_ID
    LEFT OUTER JOIN PHI_T_REL_EBA_SERVICES_ACTIVITY_TYPE resat
        ON atc.ACTIVITY_TYPE_ID = resat.ACTIVITY_TYPE_ID
    LEFT OUTER JOIN PHI_T_EBA_SERVICES es
        ON resat.EBA_SERVICES_ID = es.EBA_SERVICES_ID
    LEFT OUTER JOIN PHI_T_EBA_BUSINESS_LINE ebl
        ON ebl.CORE_BUSINESS_LINE_ID = atc.CORE_BUSINESS_LINE_ID
    LEFT OUTER JOIN PHI_T_ORGANIZATIONAL_UNIT sp
        ON sp.ORGANIZATIONAL_UNIT_ID = a.SERVICE_PROVIDER_OU_ID
    LEFT OUTER JOIN PHI_T_ORGANIZATIONAL_UNIT sr
        ON sr.ORGANIZATIONAL_UNIT_ID = a.SERVICE_RECIPIENT_OU_ID
    LEFT OUTER JOIN PHI_T_CONTRACT c
        ON c.ACTIVITY_ID = a.ACTIVITY_ID
    LEFT OUTER JOIN PHI_T_CRITICAL_FUNCTION cf
        ON cf.ACTIVITY_ID = a.ACTIVITY_ID
    LEFT OUTER JOIN PHI_T_DELIVERY_MODEL dm
        ON dm.DELIVERY_MODEL_ID = a.DELIVERY_MODEL_ID
    LEFT OUTER JOIN PHI_T_MACRO_BUSINESS_LINE mbl
        ON mbl.MACRO_BUSINESS_LINE_ID = a.MACRO_BUSINESS_LINE_ID
    LEFT OUTER JOIN PHI_T_MACRO_PROCESS mp
        ON mp.MACRO_PROCESS_ID = a.MACRO_PROCESS_ID
    LEFT OUTER JOIN PHI_T_PROCESS p
        ON p.PROCESS_ID = a.PROCESS_ID
    LEFT OUTER JOIN PHI_T_SUB_PROCESS sp_sub
        ON sp_sub.SUB_PROCESS_ID = a.SUB_PROCESS_ID
    LEFT OUTER JOIN PHI_T_ACTIVITY_CATEGORY ac
        ON ac.ACTIVITY_CATEGORY_ID = a.ACTIVITY_CATEGORY_ID
GROUP BY
    a.ACTIVITY_ID,
    es.EBA_SERVICES_ID,
    a.ACTIVITY_LABEL,
    a.ACTIVITY_DESCRIPTION,
    sp.ORGANIZATIONAL_UNIT_NAME,
    sp.ORGANIZATIONAL_UNIT_CODE,
    sr.ORGANIZATIONAL_UNIT_NAME,
    sr.ORGANIZATIONAL_UNIT_CODE,
    dm.DELIVERY_MODEL_NAME,
    ebl.CORE_BUSINESS_LINE_ID,
    a.SUBSTITUTABILITY,
    a.COST_INFO,
    c.CONTRACT_ID,
    a.RESOLUTION_CLAUSE,
    a.COUNTRY,
    mbl.MACRO_BUSINESS_LINE_NAME,
    mp.MACRO_PROCESS_NAME,
    p.PROCESS_NAME,
    sp_sub.SUB_PROCESS_NAME,
    ac.ACTIVITY_CATEGORY_NAME;
COMMIT;

END INSERT_INFO_REPORT_SERVICE_CATALOGUE;
------------------------------------------------------------------------------------------------------------------

PROCEDURE MAIN_SERVICE_CATALOGUE IS
BEGIN
TRUNCATE_SERVICE_CATALOGUE();
INSERT_INFO_REPORT_SERVICE_CATALOGUE();
END MAIN_SERVICE_CATALOGUE;
------------------------------------------------------------------------------------------------------------------

END P_REPORT_SERVICE_CATALOGUE;
