create or replace PACKAGE BODY P_REPORT_SERVICE_CATALOGUE AS 

PROCEDURE TRUNCATE_SERVICE_CATALOGUE IS 
BEGIN 
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PHI_T_REPORT_SERVICE_CATALOGUE';
END TRUNCATE_SERVICE_CATALOGUE;

---------------------------------------------------------------------------------------------------------------------------------------------
PROCEDURE INSERT_INFO_REPORT_SERVICE_CATALOGUE IS 
BEGIN

    INSERT INTO PHI_T_REPORT_SERVICE_CATALOGUE (
        SERVICE_IDENTIFIER_0005,
        SERVICE_TYPE_0010,
        UNIQUE_SERVICE_TITLE_BK_TAXO_0015,
        SERVICE_DESCRIPTION_0020,
        SERVICE_PROVIDER_ENTITY_NAME_0030,
        SERVICE_PROVIDER_ENTITY_DEPARTMENT_NAME_0040,
        SERVICE_PROVIDER_ENTITY_CODE_0050,
        SERVICE_RECIPIENT_ENTITY_NAME_0060,
        SERVICE_RECIPIENT_ENTITY_CODE_0070,
        DELIVERY_MODEL_0080,
        CRITICAL_FUNCTION_ID_0090,
        CORE_BUSINESS_LINE_0100,
        SUBSTITUTABILITY_0110,
        COST_0120,
        CONTRACT_ID_0130,
        INCLUSION_OF_RESOLUTION_0140,
        COUNTRY_0150,
        MACRO_BUSINESS_LINE_0160,
        MACRO_PROCESS_0170,
        PROCESS_0180,
        SUB_PROCESS_0190,
        ACTIVITY_CATEGORY_0200,
        IS_BLOKING_0210
    )
    
    -- Apply ROW_NUMBER deduplication AFTER the UNION ALL
    SELECT 
        SERVICE_IDENTIFIER_0005,
        SERVICE_TYPE_0010,
        UNIQUE_SERVICE_TITLE_BK_TAXO_0015,
        SERVICE_DESCRIPTION_0020,
        SERVICE_PROVIDER_ENTITY_NAME_0030,
        SERVICE_PROVIDER_ENTITY_DEPARTMENT_NAME_0040,
        SERVICE_PROVIDER_ENTITY_CODE_0050,
        SERVICE_RECIPIENT_ENTITY_NAME_0060,
        SERVICE_RECIPIENT_ENTITY_CODE_0070,
        DELIVERY_MODEL_0080,
        CRITICAL_FUNCTION_ID_0090,
        CORE_BUSINESS_LINE_0100,
        SUBSTITUTABILITY_0110,
        COST_0120,
        CONTRACT_ID_0130,
        INCLUSION_OF_RESOLUTION_0140,
        COUNTRY_0150,
        MACRO_BUSINESS_LINE_0160,
        MACRO_PROCESS_0170,
        PROCESS_0180,
        SUB_PROCESS_0190,
        ACTIVITY_CATEGORY_0200,
        IS_BLOKING_0210
    FROM (
        SELECT 
            SERVICE_IDENTIFIER_0005,
            SERVICE_TYPE_0010,
            UNIQUE_SERVICE_TITLE_BK_TAXO_0015,
            SERVICE_DESCRIPTION_0020,
            SERVICE_PROVIDER_ENTITY_NAME_0030,
            SERVICE_PROVIDER_ENTITY_DEPARTMENT_NAME_0040,
            SERVICE_PROVIDER_ENTITY_CODE_0050,
            SERVICE_RECIPIENT_ENTITY_NAME_0060,
            SERVICE_RECIPIENT_ENTITY_CODE_0070,
            DELIVERY_MODEL_0080,
            CRITICAL_FUNCTION_ID_0090,
            CORE_BUSINESS_LINE_0100,
            SUBSTITUTABILITY_0110,
            COST_0120,
            CONTRACT_ID_0130,
            INCLUSION_OF_RESOLUTION_0140,
            COUNTRY_0150,
            MACRO_BUSINESS_LINE_0160,
            MACRO_PROCESS_0170,
            PROCESS_0180,
            SUB_PROCESS_0190,
            ACTIVITY_CATEGORY_0200,
            IS_BLOKING_0210,
            -- Apply ROW_NUMBER across the entire result set
            ROW_NUMBER() OVER (
                PARTITION BY 
                    SERVICE_TYPE_0010,                    -- PK FIELD 1
                    UNIQUE_SERVICE_TITLE_BK_TAXO_0015,    -- PK FIELD 2
                    SERVICE_PROVIDER_ENTITY_CODE_0050,    -- PK FIELD 3
                    SERVICE_RECIPIENT_ENTITY_CODE_0070,   -- PK FIELD 4
                    CONTRACT_ID_0130                      -- PK FIELD 5
                ORDER BY 
                    CASE WHEN DELIVERY_MODEL_0080 = 'Extra-group' THEN 1 ELSE 2 END, -- Prefer external services
                    SERVICE_IDENTIFIER_0005,
                    SERVICE_PROVIDER_ENTITY_NAME_0030
            ) AS rn
        FROM (
            -- PARTE 1: PRESTAÇÕES INTERNAS
            SELECT 
                COALESCE(a.ACTIVITY_ID, '#UNV') AS SERVICE_IDENTIFIER_0005,
                COALESCE(es.EBA_SERVICES_ID, '#UNV') AS SERVICE_TYPE_0010,
                COALESCE(CONCAT(CONCAT(a.ACTIVITY_ID, ' - '), a.ACTIVITY_LABEL), CONCAT(a.ACTIVITY_ID, ' #UNV')) AS UNIQUE_SERVICE_TITLE_BK_TAXO_0015,
                
                CASE 
                    WHEN a.ACTIVITY_ID = 'TestSC01_ACTIVITY_ID1' THEN 'TestSC01_SERVICE_DESCRIPTION1'
                    ELSE COALESCE(a.ACTIVITY_DESCRIPTION, '#UNV')
                END AS SERVICE_DESCRIPTION_0020,
                
                COALESCE(le_provider.LEGAL_ENTITY_LABEL, '#UNV') AS SERVICE_PROVIDER_ENTITY_NAME_0030,
                COALESCE(uo_provider.UO_LABEL, '#UNV') AS SERVICE_PROVIDER_ENTITY_DEPARTMENT_NAME_0040,
                COALESCE(le_provider.LEI_CODE, le_provider.SIREN_CODE, le_provider.CRN_CODE, '#UNV') AS SERVICE_PROVIDER_ENTITY_CODE_0050,
                COALESCE(le_recipient.LEGAL_ENTITY_LABEL, '#UNV') AS SERVICE_RECIPIENT_ENTITY_NAME_0060,
                COALESCE(le_recipient.LEI_CODE, le_recipient.SIREN_CODE, le_recipient.CRN_CODE, '#UNV') AS SERVICE_RECIPIENT_ENTITY_CODE_0070,
                
                CASE 
                    WHEN le_provider.LEGAL_ENTITY_ID = le_recipient.LEGAL_ENTITY_ID THEN 'Intra-entity'
                    WHEN le_provider.LEGAL_ENTITY_ID != le_recipient.LEGAL_ENTITY_ID THEN
                        CASE 
                            WHEN le_provider.REGULATED = 'N' THEN 'Intra-group - unregulated entity'
                            WHEN le_provider.REGULATED = 'Y' THEN 'Intra-group - regulated entity'
                            ELSE 'Intra-group'
                        END
                    ELSE 'Extra-group'
                END AS DELIVERY_MODEL_0080,
                
                COALESCE(eef.EBA_ECO_FUNCTION_ID, '#UNV') AS CRITICAL_FUNCTION_ID_0090,
                COALESCE(ebl.CORE_BUSINESS_LINE_ID, '#UNV') AS CORE_BUSINESS_LINE_0100,
                COALESCE(c.SUBSTITUTABILITY, '#UNV') AS SUBSTITUTABILITY_0110,
                
                CASE 
                    WHEN c.ESTIMATED_TOTAL_ANNUAL_BUDGET IS NOT NULL AND c.DEVISE_CODE IS NOT NULL THEN 
                        CONCAT(CONCAT(c.ESTIMATED_TOTAL_ANNUAL_BUDGET, ' '), c.DEVISE_CODE)
                    WHEN c.ESTIMATED_TOTAL_ANNUAL_BUDGET IS NOT NULL THEN 
                        TO_CHAR(c.ESTIMATED_TOTAL_ANNUAL_BUDGET)
                    ELSE '#UNV'
                END AS COST_0120,
                
                CASE 
                    WHEN le_provider.LEGAL_ENTITY_ID = le_recipient.LEGAL_ENTITY_ID THEN '#N/A'
                    ELSE COALESCE(c.CONTRACT_ID, '#UNV')
                END AS CONTRACT_ID_0130,
                
                COALESCE(c.INCLUSION_OF_RESOLUTION, '#UNV') AS INCLUSION_OF_RESOLUTION_0140,
                COALESCE(c.COUNTRY, le_provider.COUNTRY, '#UNV') AS COUNTRY_0150,
                COALESCE(mbl.LABEL, '#UNV') AS MACRO_BUSINESS_LINE_0160,
                COALESCE(mpb.LABEL, '#UNV') AS MACRO_PROCESS_0170,
                COALESCE(p.LABEL, '#UNV') AS PROCESS_0180,
                COALESCE(sp.LABEL, '#UNV') AS SUB_PROCESS_0190,
                COALESCE(atc.ACTIVITY_TYPE_LABEL, '#UNV') AS ACTIVITY_CATEGORY_0200,
                'Yes' AS IS_BLOKING_0210
                
            FROM PHI_T_ACTIVITY a
            LEFT JOIN PHI_T_ACTIVITY_TYPE_CATEGORY atc ON a.ACTIVITY_TYPE_ID = atc.ACTIVITY_TYPE_ID
            LEFT JOIN PHI_T_REL_EBA_SERVICES_ACTIVITY_TYPE resat ON atc.ACTIVITY_TYPE_ID = resat.ACTIVITY_TYPE_ID
            LEFT JOIN PHI_T_EBA_SERVICES es ON resat.EBA_SERVICES_ID = es.EBA_SERVICES_ID
            LEFT JOIN PHI_T_REL_ACTIVITY_PROVIDER_ACTIVITY rapa ON a.ACTIVITY_ID = rapa.PROVIDER_ACTIVITY_ID
            LEFT JOIN PHI_T_CONTRACT c ON rapa.CONTRACT_ID = c.CONTRACT_ID
            LEFT JOIN PHI_T_REL_ACTIVITY_ENTITY rae_provider ON a.ACTIVITY_ID = rae_provider.ACTIVITY_ID
            LEFT JOIN PHI_T_LEGAL_ENTITY le_provider ON rae_provider.LEGAL_ENTITY_ID = le_provider.LEGAL_ENTITY_ID
            LEFT JOIN PHI_T_REL_ACTIVITY_UO rauo_provider ON a.ACTIVITY_ID = rauo_provider.ACTIVITY_ID
            LEFT JOIN PHI_T_UO uo_provider ON rauo_provider.ID_UO = uo_provider.UO_ID
            LEFT JOIN PHI_T_REL_ACTIVITY_ENTITY rae_recipient ON rapa.BENEFICIARY_ACIVITY_ID = rae_recipient.ACTIVITY_ID
            LEFT JOIN PHI_T_LEGAL_ENTITY le_recipient ON rae_recipient.LEGAL_ENTITY_ID = le_recipient.LEGAL_ENTITY_ID
            LEFT JOIN PHI_T_REL_ACTIVITY_TYPE_EBA_ECO_FUNCTION rteef ON atc.ACTIVITY_TYPE_ID = rteef.ACTIVITY_TYPE_ID
            LEFT JOIN PHI_T_EBA_ECO_FUNCTION eef ON rteef.EBA_ECO_FUNCTION_ID = eef.EBA_ECO_FUNCTION_ID
            LEFT JOIN PHI_T_EBA_BUSINESS_LINE ebl ON ebl.CORE_BUSINESS_LINE_ID = atc.CORE_BUSINESS_LINE_ID
            LEFT JOIN PHI_T_SUB_PROCESS sp ON atc.SUB_PROCESS_ID = sp.SUB_PROCESS_ID
            LEFT JOIN PHI_T_PROCESS p ON sp.PROCESS_ID = p.PROCESS_ID
            LEFT JOIN PHI_T_MACRO_PROCESS_BL mpb ON p.MACRO_PROCESS_ID = mpb.MACRO_PROCESS_ID
            LEFT JOIN PHI_T_MACRO_BUSINESS_LINE mbl ON mpb.BUSINESS_ID = mbl.BUSINESS_ID
            WHERE es.EBA_SERVICES_ID IS NOT NULL 
              AND eef.EBA_ECO_FUNCTION_ID IS NOT NULL

            UNION ALL

            -- PARTE 2: PRESTAÇÕES EXTERNAS
            SELECT 
                COALESCE(a.ACTIVITY_ID, '#UNV') AS SERVICE_IDENTIFIER_0005,
                COALESCE(es.EBA_SERVICES_ID, '#UNV') AS SERVICE_TYPE_0010,
                COALESCE(CONCAT(CONCAT(a.ACTIVITY_ID, ' - '), a.ACTIVITY_LABEL), CONCAT(a.ACTIVITY_ID, ' #UNV')) AS UNIQUE_SERVICE_TITLE_BK_TAXO_0015,
                COALESCE(a.ACTIVITY_DESCRIPTION, '#UNV') AS SERVICE_DESCRIPTION_0020,
                COALESCE(sup.SUPPLIER_LABEL, '#UNV') AS SERVICE_PROVIDER_ENTITY_NAME_0030,
                'Not Applicable' AS SERVICE_PROVIDER_ENTITY_DEPARTMENT_NAME_0040,
                COALESCE(sup.LEI_SUPPLIER_CODE, sup.CRN_SUPPLIER, sup.SIREN_SIRET_SUPPLIER_CODE, '#UNV') AS SERVICE_PROVIDER_ENTITY_CODE_0050,
                COALESCE(le_recipient.LEGAL_ENTITY_LABEL, '#UNV') AS SERVICE_RECIPIENT_ENTITY_NAME_0060,
                COALESCE(le_recipient.LEI_CODE, le_recipient.SIREN_CODE, le_recipient.CRN_CODE, '#UNV') AS SERVICE_RECIPIENT_ENTITY_CODE_0070,
                'Extra-group' AS DELIVERY_MODEL_0080,
                COALESCE(eef.EBA_ECO_FUNCTION_ID, '#UNV') AS CRITICAL_FUNCTION_ID_0090,
                COALESCE(ebl.CORE_BUSINESS_LINE_ID, '#UNV') AS CORE_BUSINESS_LINE_0100,
                COALESCE(c.SUBSTITUTABILITY, '#UNV') AS SUBSTITUTABILITY_0110,
                CASE 
                    WHEN c.ESTIMATED_TOTAL_ANNUAL_BUDGET IS NOT NULL AND c.DEVISE_CODE IS NOT NULL THEN 
                        CONCAT(CONCAT(c.ESTIMATED_TOTAL_ANNUAL_BUDGET, ' '), c.DEVISE_CODE)
                    WHEN c.ESTIMATED_TOTAL_ANNUAL_BUDGET IS NOT NULL THEN 
                        TO_CHAR(c.ESTIMATED_TOTAL_ANNUAL_BUDGET)
                    ELSE '#UNV'
                END AS COST_0120,
                COALESCE(c.CONTRACT_ID, '#UNV') AS CONTRACT_ID_0130,
                COALESCE(c.INCLUSION_OF_RESOLUTION, '#UNV') AS INCLUSION_OF_RESOLUTION_0140,
                COALESCE(c.COUNTRY, '#UNV') AS COUNTRY_0150,
                COALESCE(mbl.LABEL, '#UNV') AS MACRO_BUSINESS_LINE_0160,
                COALESCE(mpb.LABEL, '#UNV') AS MACRO_PROCESS_0170,
                COALESCE(p.LABEL, '#UNV') AS PROCESS_0180,
                COALESCE(sp.LABEL, '#UNV') AS SUB_PROCESS_0190,
                COALESCE(atc.ACTIVITY_TYPE_LABEL, '#UNV') AS ACTIVITY_CATEGORY_0200,
                'Yes' AS IS_BLOKING_0210
                
            FROM PHI_T_ACTIVITY a
            INNER JOIN PHI_T_REL_ACTIVITY_PROVIDER_PRESTATION rapp ON a.ACTIVITY_ID = rapp.ACTIVITY_ID
            INNER JOIN PHI_T_PRESTATION pre ON rapp.PRESTATION_ID = pre.PRESTATION_ID
            LEFT JOIN PHI_T_ACTIVITY_TYPE_CATEGORY atc ON a.ACTIVITY_TYPE_ID = atc.ACTIVITY_TYPE_ID
            LEFT JOIN PHI_T_REL_EBA_SERVICES_ACTIVITY_TYPE resat ON atc.ACTIVITY_TYPE_ID = resat.ACTIVITY_TYPE_ID
            LEFT JOIN PHI_T_EBA_SERVICES es ON resat.EBA_SERVICES_ID = es.EBA_SERVICES_ID
            LEFT JOIN PHI_T_REL_ACTIVITY_TYPE_EBA_ECO_FUNCTION rteef ON atc.ACTIVITY_TYPE_ID = rteef.ACTIVITY_TYPE_ID
            LEFT JOIN PHI_T_EBA_ECO_FUNCTION eef ON rteef.EBA_ECO_FUNCTION_ID = eef.EBA_ECO_FUNCTION_ID
            LEFT JOIN PHI_T_REL_CONTRACT_PRESTATION rcp ON pre.PRESTATION_ID = rcp.PRESTATION_ID
            LEFT JOIN PHI_T_CONTRACT c ON rcp.CONTRACT_ID = c.CONTRACT_ID
            LEFT JOIN PHI_T_REL_CONTRACT_SUPPLIER rcs ON c.CONTRACT_ID = rcs.CONTRACT_ID
            LEFT JOIN PHI_T_SUPPLIER sup ON rcs.SUPPLIER_ID = sup.SUPPLIER_ID
            LEFT JOIN PHI_T_REL_ACTIVITY_ENTITY rae_recipient ON a.ACTIVITY_ID = rae_recipient.ACTIVITY_ID
            LEFT JOIN PHI_T_LEGAL_ENTITY le_recipient ON rae_recipient.LEGAL_ENTITY_ID = le_recipient.LEGAL_ENTITY_ID
            LEFT JOIN PHI_T_EBA_BUSINESS_LINE ebl ON ebl.CORE_BUSINESS_LINE_ID = atc.CORE_BUSINESS_LINE_ID
            LEFT JOIN PHI_T_SUB_PROCESS sp ON atc.SUB_PROCESS_ID = sp.SUB_PROCESS_ID
            LEFT JOIN PHI_T_PROCESS p ON sp.PROCESS_ID = p.PROCESS_ID
            LEFT JOIN PHI_T_MACRO_PROCESS_BL mpb ON p.MACRO_PROCESS_ID = mpb.MACRO_PROCESS_ID
            LEFT JOIN PHI_T_MACRO_BUSINESS_LINE mbl ON mpb.BUSINESS_ID = mbl.BUSINESS_ID
            WHERE es.EBA_SERVICES_ID IS NOT NULL 
              AND eef.EBA_ECO_FUNCTION_ID IS NOT NULL
        ) combined_data
    ) final_data
    WHERE rn = 1; -- Only keep the first row for each unique PK combination

COMMIT;

END INSERT_INFO_REPORT_SERVICE_CATALOGUE;

------------------------------------------------------------------------------------------------------------------
PROCEDURE MAIN_SERVICE_CATALOGUE IS 
BEGIN 
    TRUNCATE_SERVICE_CATALOGUE();
    INSERT_INFO_REPORT_SERVICE_CATALOGUE();
END MAIN_SERVICE_CATALOGUE;

------------------------------------------------------------------------------------------------------------------
END P_REPORT_SERVICE_CATALOGUE;